[package]
name = "wuphf"
version = "0.1.0"
license = "AGPLv3"
authors = ["Patrick O'Doherty <p@trickod.com>"]

[dependencies]
request = "0.0.8"
rustc-serialize = "0.3"
url = "0.2.37"
log = "0.3.2"
env_logger = "0.3"
